# /// script
# requires-python = ">=3.11"
# dependencies = []
# ///
"""multi-step-python — demonstrator module with two python steps.

Shows how a module.py dispatches on args.step when a manifest declares
multiple [[steps]] of kind=python.

Steps:
  scaffold  — writes a bare-bones README.md (create-if-absent)
  configure — writes a .project-name sentinel file (reconcile=true: overwrite)

The runner calls this script TWICE:
  uv run module.py --plan plan.json --step scaffold
  uv run module.py --plan plan.json --step configure

Invocation contract: --plan <frozen_plan.json> --step <id> [--inspect]
"""

from __future__ import annotations

import argparse
import importlib.util
import os
import sys
from pathlib import Path


def _load_sdk():
    """Load the runner SDK. Fast path: `import sdk` (the executor puts the runner
    dir on PYTHONPATH — spec 005). Fallback: load by file path for direct
    invocation outside the executor (e.g. functional tests)."""
    try:
        import sdk  # noqa: PLC0415
        return sdk
    except ModuleNotFoundError:
        pass
    # Fallback: locate sdk.py by path (PLUGIN_ROOT / CLAUDE_PLUGIN_ROOT, or __file__-relative).
    plugin_root = os.environ.get("PLUGIN_ROOT") or os.environ.get("CLAUDE_PLUGIN_ROOT")
    if plugin_root:
        sdk_path = Path(plugin_root) / "runner" / "sdk.py"
        if not sdk_path.is_file():
            sdk_path = Path(plugin_root) / "skills" / "project-setup" / "runner" / "sdk.py"
    else:
        sdk_path = Path(__file__).resolve().parents[2] / "runner" / "sdk.py"
    spec = importlib.util.spec_from_file_location("sdk", sdk_path)
    assert spec and spec.loader, f"cannot locate runner SDK at {sdk_path}"
    mod = importlib.util.module_from_spec(spec)
    sys.modules["sdk"] = mod          # register BEFORE exec_module (the @dataclass(Exception) footgun)
    spec.loader.exec_module(mod)
    return mod
def _do_scaffold(sdk, inputs, args) -> int:
    """scaffold step: write a bare-bones README.md (create-if-absent)."""
    project_name = inputs.get_str("project_name", default="my-project")
    body = f"# {project_name}\n\nGenerated by multi-step-python example module.\n"

    diff = sdk.idempotent_write(
        "README.md",
        body,
        reconcile=False,   # write-if-absent; matches module reconcile=true per-step override
        inspect=args.inspect,
    )

    files_written = [diff.path] if diff.kind in ("create", "modify") else []
    sdk.emit_result(sdk.ModuleResult(
        module_id="multi-step-python",
        step_id=args.step,
        status="ok",
        files_written=files_written,
        diffs=[diff],
    ))
    return 0


def _do_configure(sdk, inputs, args) -> int:
    """configure step: write a .project-name sentinel (reconcile=true: always current)."""
    project_name = inputs.get_str("project_name", default="my-project")
    enable_ci = inputs.get_bool("enable_ci", default=False)

    lines = [f"project_name={project_name}\n", f"enable_ci={str(enable_ci).lower()}\n"]
    body = "".join(lines)

    diff = sdk.idempotent_write(
        ".project-name",
        body,
        reconcile=True,    # always overwrite-to-match (keep in sync with inputs)
        inspect=args.inspect,
    )

    files_written = [diff.path] if diff.kind in ("create", "modify") else []
    sdk.emit_result(sdk.ModuleResult(
        module_id="multi-step-python",
        step_id=args.step,
        status="ok",
        files_written=files_written,
        diffs=[diff],
    ))
    return 0


# ── dispatch table ────────────────────────────────────────────────────────── #

STEP_HANDLERS = {
    "scaffold":  _do_scaffold,
    "configure": _do_configure,
}


def main() -> int:
    ap = argparse.ArgumentParser(description="multi-step-python example module")
    ap.add_argument("--plan", required=True, help="path to the frozen plan.json")
    ap.add_argument("--step", required=True, help="step id to run")
    ap.add_argument("--inspect", action="store_true", help="dry pass: preview, no write")
    args = ap.parse_args()

    handler = STEP_HANDLERS.get(args.step)
    if handler is None:
        print(
            f"Unknown step: {args.step!r}. Valid steps: {list(STEP_HANDLERS)}",
            file=sys.stderr,
        )
        return 1

    sdk = _load_sdk()
    inputs = sdk.load_frozen_inputs(args.plan, module_id="multi-step-python")
    return handler(sdk, inputs, args)


if __name__ == "__main__":
    raise SystemExit(main())
