# /// script
# requires-python = ">=3.11"
# dependencies = []
# ///
"""env-example — write a .env.example from the resolved stack.

The agent step (resolve) derives a structured list of env var definitions
(env_keys) from the frozen stack inputs (framework_python, framework_ts,
extra_env_hints). The gate step (preview) shows the list for one-time human
review. This python step (write) validates each entry and writes .env.example
with placeholder tokens only — never a real credential.

Safety invariant (spec 011 FR-008/009/012):
  - Output path is HARD-CODED to .env.example (the agent cannot redirect it).
  - Every placeholder is validated with sdk.looks_like_secret before any write.
  - A placeholder that looks like a real credential is a hard error — nothing
    is written.
  - A secret_bool=true entry with an empty placeholder is also a hard error.

Determinism (spec 011 FR-014):
  - Entries are sorted alphabetically by name.
  - Same frozen env_keys → identical bytes on every run (Tier-1 guarantee).

Invoked by the runner as:
    uv run module.py --plan <frozen_plan.json> --step <write> [--inspect]
"""

from __future__ import annotations

import argparse
import importlib.util
import os
import re
import sys
from pathlib import Path


def _load_sdk():
    """Load the runner SDK. Fast path: `import sdk` (the executor puts the runner
    dir on PYTHONPATH — spec 005). Fallback: load by file path for direct
    invocation outside the executor (e.g. functional tests)."""
    try:
        import sdk  # noqa: PLC0415
        return sdk
    except ModuleNotFoundError:
        pass
    # Fallback: locate sdk.py by path (PLUGIN_ROOT, or __file__-relative).
    plugin_root = os.environ.get("PLUGIN_ROOT") or os.environ.get("CLAUDE_PLUGIN_ROOT")
    if plugin_root:
        sdk_path = Path(plugin_root) / "runner" / "sdk.py"
        if not sdk_path.is_file():
            sdk_path = Path(plugin_root) / "skills" / "project-setup" / "runner" / "sdk.py"
    else:
        sdk_path = Path(__file__).resolve().parents[3] / "skills" / "project-setup" / "runner" / "sdk.py"
    spec = importlib.util.spec_from_file_location("sdk", sdk_path)
    assert spec and spec.loader, f"cannot locate runner SDK at {sdk_path}"
    mod = importlib.util.module_from_spec(spec)
    sys.modules["sdk"] = mod          # register BEFORE exec_module (the @dataclass(Exception) footgun)
    spec.loader.exec_module(mod)
    return mod


# Env var name validation: must be SCREAMING_SNAKE_CASE starting with a letter.
_NAME_RE = re.compile(r"^[A-Z][A-Z0-9_]*$")

# Fixed output path — never read from inputs (spec 011 FR-012, D).
_OUTPUT_PATH = ".env.example"

# Fixed preamble — two lines, always present (spec 011 FR-011).
_PREAMBLE = (
    "# .env.example — generated by project-setup; fill in values before running.\n"
    "# DO NOT commit real values to version control.\n"
)


# --------------------------------------------------------------------------- #
# Step handlers                                                                #
# --------------------------------------------------------------------------- #

def _do_write(sdk, inputs, args) -> int:
    """write step: validate env_keys and write .env.example idempotently."""
    env_keys: list = inputs.get_list("env_keys", default=[])
    warnings: list[str] = []
    valid_entries: list[dict] = []

    for entry in env_keys:
        if not isinstance(entry, dict):
            warnings.append(f"WARN: env_keys entry is not a dict — skipped: {entry!r}")
            continue

        name = entry.get("name", "")
        placeholder = entry.get("placeholder", "")
        comment = entry.get("comment", "")
        secret_bool = bool(entry.get("secret_bool", False))

        # FR-010: validate name against SCREAMING_SNAKE_CASE.
        if not isinstance(name, str) or not _NAME_RE.fullmatch(name):
            warnings.append(
                f"WARN: env_keys entry has invalid name {name!r} "
                f"(must match ^[A-Z][A-Z0-9_]*$) — skipped"
            )
            continue

        # FR-009: secret_bool=true with empty placeholder is a hard error.
        if secret_bool and (not isinstance(placeholder, str) or placeholder == ""):
            result = sdk.ModuleResult(
                module_id="env-example",
                step_id=args.step,
                status="error",
                error=sdk.SetupError(
                    error_code=sdk.ErrorCode.INPUT_VALUE_INVALID,
                    module_id="env-example",
                    expected="non-empty placeholder for secret-class env var",
                    received=f"name={name!r}, placeholder='' (secret_bool=true)",
                    how_to_fix=(
                        f"The env var {name!r} is marked secret_bool=true but has an empty "
                        f"placeholder. Provide a descriptive placeholder token "
                        f"(e.g. 'your-{name.lower().replace('_', '-')}-here') — never a real value."
                    ),
                ).to_dict(),
            )
            sdk.emit_result(result)
            return 1

        # FR-008: hard-refuse any placeholder that looks like a real secret.
        secret_label = sdk.looks_like_secret(placeholder)
        if secret_label is not None:
            result = sdk.ModuleResult(
                module_id="env-example",
                step_id=args.step,
                status="error",
                error=sdk.SetupError(
                    error_code=sdk.ErrorCode.INPUT_VALUE_INVALID,
                    module_id="env-example",
                    expected="placeholder token (not a real credential)",
                    received=f"name={name!r}, placeholder matches {secret_label!r}",
                    how_to_fix=(
                        f"The placeholder for {name!r} looks like a real {secret_label} "
                        f"({placeholder!r}). Replace it with a descriptive token such as "
                        f"'your-{name.lower().replace('_', '-')}-here'. "
                        f"Never write real credentials into .env.example."
                    ),
                ).to_dict(),
            )
            sdk.emit_result(result)
            return 1

        # Sanitize newlines in placeholder (edge case from spec).
        if isinstance(placeholder, str) and "\n" in placeholder:
            sanitized = placeholder.replace("\n", " ")
            warnings.append(
                f"WARN: placeholder for {name!r} contained newlines — replaced with spaces"
            )
            placeholder = sanitized

        valid_entries.append({
            "name": name,
            "placeholder": placeholder if isinstance(placeholder, str) else "",
            "comment": comment if isinstance(comment, str) else "",
            "secret_bool": secret_bool,
        })

    # FR-011: sort by name (ASCIIbetical / Python sorted()).
    valid_entries.sort(key=lambda e: e["name"])

    # Build the file body: fixed preamble + one KEY=placeholder line per entry.
    lines = [_PREAMBLE]
    for e in valid_entries:
        line = f"{e['name']}={e['placeholder']}"
        if e["comment"]:
            line += f"  # {e['comment']}"
        lines.append(line + "\n")

    body = "".join(lines)

    # FR-012: path is HARD-CODED — never from inputs.
    diff = sdk.idempotent_write(
        _OUTPUT_PATH,
        body,
        reconcile=inputs.reconcile,
        inspect=args.inspect,
    )

    files_written = [diff.path] if diff.kind in ("create", "modify") else []
    result = sdk.ModuleResult(
        module_id="env-example",
        step_id=args.step,
        status="ok",
        files_written=files_written,
        diffs=[diff],
        warnings=warnings,
    )
    sdk.emit_result(result)
    return 0


STEP_HANDLERS = {
    "write": _do_write,
    # "resolve" is kind=agent  — handled by the runner's Tier-2 agent subsystem.
    # "preview" is kind=gate   — handled by the runner's gate subsystem.
}


def main() -> int:
    ap = argparse.ArgumentParser(description="env-example module")
    ap.add_argument("--plan", required=True, help="path to the frozen plan.json")
    ap.add_argument("--step", required=True, help="step id to run")
    ap.add_argument("--inspect", action="store_true", help="dry pass: preview, no write")
    args = ap.parse_args()

    handler = STEP_HANDLERS.get(args.step)
    if handler is None:
        print(
            f"Unknown step: {args.step!r}. "
            f"Python-handled steps: {list(STEP_HANDLERS)}. "
            f"Agent/gate steps are dispatched by the runner, not by module.py.",
            file=sys.stderr,
        )
        return 1

    sdk = _load_sdk()
    inputs = sdk.load_frozen_inputs(args.plan, module_id="env-example")
    return handler(sdk, inputs, args)


if __name__ == "__main__":
    raise SystemExit(main())
